### PR TITLE
Update Medium editor files to version 4.2.0

### PR DESCRIPTION
**Pull request by arielsvn**

### CODE REVIEW

**Comment by marjinal1st** [comment]
Thanks for PR.

Unfortunately I'm having troubles for maintaining this gem, due to some reasons (school, projects etc.). If you would like to keep it update, I can authorize you to push to **develop/master** and **RubyGems**.

**Comment by arielsvn** [comment]
Sure it's not a problem. I'm using it on a project so it would help if it was updated.

**Comment by marjinal1st** [comment]
I merged the PR for once and added you as a collaborator. You can push to develop/master anytime now.

Then you need te release versions, which I used to do it with [git-flow](http://danielkummer.github.io/git-flow-cheatsheet/) and [Semantic Versioning](http://semver.org/)

Also I'm adding you to Rubygems as a collaborator on your email.

**Comment by arielsvn** [comment]
OK thanks :+1:

**Pull request merged**
