### PR TITLE
Update version medium-editor for 5.14.4

### PR DESCRIPTION
**Pull request by gabrielmedina**

### CODE REVIEW

**Comment by marjinal1st** [comment]
As you can read in the README.md, I no longer maintain this gem, so [this](https://github.com/marjinal1st/medium-editor-rails/pull/9/commits/e3bc5a32921a76eb9333240635f53bae670ab692#diff-04c6e90faac2675aa89e2176d2eec7d8R5) is unnecessary, not even for a sincere reference.

If you like, I add you as a collaborator (so you can commit directly or accept PRs) or transfer the ownership of this repository and gem to you directly. Otherwise I won't accept any PR.

**Comment by gabrielmedina** [comment]
Sorry,
You could put me as a collaborator then?

**Comment by marjinal1st** [comment]
> Sorry,

Nothing to be sorry.

> You could put me as a collaborator then?

I just did. Now you can commit and accept PRs as you like. Please sign-up at [RubyGems](https://rubygems.org/) so I can add you as gem collaborator.

**Comment by gabrielmedina** [comment]
Ok, thanks.

I'am `gabrielmedina` in RubyGems.

**Comment by marjinal1st** [comment]
Alright, I just added you as gem collaborator too. Now feel free to push newer versions, commit or merge PRs (including this one)

**Comment by gabrielmedina** [comment]
Thank you

**Pull request closed without merging**
